all: prog3_server prog3_observer prog3_participant
CC=gcc
CFLAGS=-g

prog3_server: prog3_server.c
	$(CC) -o prog3_server prog3_server.c $(CFLAGS)

prog3_observer: prog3_observer.c
	$(CC) -o prog3_observer prog3_observer.c $(CFLAGS)

prog3_participant: prog3_participant.c
	$(CC) -o prog3_participant prog3_participant.c $(CFLAGS)
